[package]
name = "currency-exchange"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "test"
path = "src/main.rs"

[dependencies]
dotenv = "0.15.0"
reqwest = "0.12"
serde_json = "1.0.114"
tokio = { version = "1", features = ["full"]}
openssl = { version = "0.10", features = ["vendored"] }